#+AUTHOR: Richie Kirchofer

* Resolve Face

This package provides ~face-attribute+~ which is an enhancement of ~face-attribute~ in that ~face-attribute+~ supports anonymous face specs.

This package also provides ~resolve-face-attributes~ which calls ~face-attribute+~ for each face attribute giving you a fully resolved, normalized face spec.

#+begin_src emacs-lisp :results verbatim
(resolve-face-attributes 'treemacs-root-remote-face nil t)
#+end_src

: ((:height . 1.2) (:weight . bold) (:foreground . "#c678dd"))

#+begin_src emacs-lisp :results verbatim
(resolve-face-attributes 'treemacs-root-remote-face nil 'default)
#+end_src

: ((:family . "Adwaita Mono") (:foundry . "UKWN") (:width . normal) (:height . 189) (:weight . bold) (:slant . normal) (:underline) (:overline) (:extend) (:strike-through) (:box) (:inverse-video) (:foreground . "#c678dd") (:background . "#282c34") (:stipple) (:inherit))

* This package is used in [[https://github.com/rgkirch/propertized-text-to-svg][propertized-text-to-svg]] to normalize a face.

* See [[https://github.com/rgkirch/my-emacs-packages][my other emacs packages]]
* License

Copyright (C) 2025 Richie Kirchofer

SPDX-License-Identifier: GPL-3.0-or-later

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
